### ISSUE TITLE
Weird version displayed on merge commit

### ISSUE THREAD

**Issue by leifg** [semantic-release/go-semantic-release#12]
The tool works great if you have a flat commit history. But when you have a merge commit from a PR, the whole commit will be taken as a name. See [the latest release of my app](https://github.com/leifg/time_tracking/releases/tag/v1.8.5).

This is due to the fact that the version name is left empty (see in [api response](https://api.github.com/repos/leifg/time_tracking/releases/7377377)).

An easy fix could be explicitly setting the name.

**Comment by christophwitzko** [comment]
Hi @leifg, thanks for reporting the issue. This looks like some weird GitHub bug, but your recommended fix sounds reasonable to me. I will try to fix that by next week.
