### ISSUE TITLE
Please support branch-specific releases

### ISSUE THREAD

**Issue by jbcpollak** [semantic-release/go-semantic-release#2]
We follow the gitflow process, and I'd like to be able to publish versions with each commit, in a branch-specific way.

For example:

The current version of my project is `1.0.0` and I'm working on a branch, `feature/foo`. I'd like to publish the project as `1.0.1-foo.1`, `1.0.1-foo.2`, `1.0.1-foo.3`.

When I merge to my develop branch, I'd like to publish `1.0.1-beta.1`. Subsequent merges would be `1.0.1-beta.2`, etc.

Finally, when I merge to the master branch, I'd like to publish `1.0.1` (or `1.1.0`, or `2.0.0` of course, depending on the commit message semantics)

Is this something this project could support?

**Comment by jbcpollak** [comment]
I was thinking more about this, `npm version` has `premajor | preminor | prepatch` support. It would be great if semantic-release could do this, possibly based on an environment variable or the git branch name.

For example, based on the commit log, we'd calculate the next version, and then depending on your branch name, we'd either set the version, or increment a pre-version.

`develop` branch would use the label `beta`, and `feature/*` branches would use * as the label version.

**Comment by christophwitzko** [comment]
Hi @jbcpollak,

this is the repository of the go version of semantic-release.
It looks like your issue is more JavaScript related, feel free to open another issue here: https://github.com/semantic-release/semantic-release/issues

Best,
Christoph

**Comment by jbcpollak** [comment]
Hi Christoph,

I was using npm as an example, but I am hoping to do the same with Docker and .tgz images as well. I was going to fork the repo and see if I can get it to do what I had in mind, would you be interested in discussing a PR once I have something working?

**Comment by christophwitzko** [comment]
@jbcpollak ops, I was too fast ☺️ Looking forward to your pull request.

**Comment by jbcpollak** [comment]
Thanks. It will take a few days probably.

**Comment by christophwitzko** [comment]
Hi @jbcpollak, I had some time to think about this. In my opinion, `semantic-release` should not force the user to use specific branch names. Instead, I came up with the idea of a `.semrelrc` file that tells `semantic-release` how it publishes the current branch. I have already implemented an tested this feature, and it works nicely: https://github.com/semantic-release/go-semantic-release#beta-release-support
Would love to hear your feedback on this one. 😊

**Comment by christophwitzko** [comment]
My next plan is to make `semantic-release` more modular for everyone so that everybody can write their own plugins.

**Comment by jbcpollak** [comment]
Hi, sorry for the delay. I can understand wanting this project not the be responsible for version names, although I generally prefer convention over configuration.

I have two thoughts about your current implementation: first, it seems like the  config file specifies both a version and a prerelease name. I'd prefer to only specify the pre-sale name and let the semantic release figure out the name. I _think_ if you follow GitFlow feature/maintenance practices this will avoid conflicting versions

Second, I'd prefer a command line switch or environment variable over a config file, since it will be easier to make dynamic (determined by the CI tools, etc), and reduces the risk of merge conflicts or accidents when merging branches.

I'll try and finish up my changes and share them for your thoughts early this week
