### ISSUE TITLE
probably should not write .npmrc

### ISSUE THREAD

**Issue by jbcpollak** [semantic-release/go-semantic-release#6]
Hi, the .npmrc being written when we enable `-update package.json` is causing problems for us. I've had to comment it out in our branch. We publish most of our packages to a 3rd party repository which uses different authentication settings. We don't set $NPM_TOKEN, and our npmrc files look different than the one hard coded in this project.

It seems to me deployment strategy is out of scope of this project, since many people will have different needs, so I don't think the project should be writing `.npmrc`. For us, we have a shell script `setupNpm.sh` that our CI tool runs that configures our permissions as necessary.

**Comment by christophwitzko** [comment]
Hey @jbcpollak, sorry for the late reply. I have released a fix for this issue. [`semantic-relases@v1.5.1`](https://github.com/semantic-release/go-semantic-release/releases/tag/v1.5.1) does not overwrite a existing `.npmrc` file.

**Comment by jbcpollak** [comment]
Thanks!
