### ISSUE TITLE
Renew let's encrypt SSL certificate

### ISSUE THREAD

**Issue by tonygaetani** [semantic-release/go-semantic-release#9]
It looks like the get-release.xyz SSL certificate expired today. It can easily be renewed with `certbot-auto renew` (there is a --dry-run option if you want to try it out).

![ssl error](http://i.imgur.com/EFRovMX.png)

**Comment by christophwitzko** [comment]
@tonygaetani Thank you so much for reporting. It looks like my auto-renew process had some issues restarting nginx. Should be fixed by now. 🙏

**Comment by tonygaetani** [comment]
@christophwitzko no problem! Maybe this is how you're doing it, but you can reload your nginx config by sending a HUP signal to the master: `sudo pkill --signal HUP nginx` or equivalent. I always loved that feature of nginx so just thought I'd share 🙂
